### ISSUE TITLE
Python transpiler

### ISSUE THREAD

**Issue by ExtReMLapin** [alexprengere/PythonBrainFuck#4]
It took me little to no time to write a Lua transpiler for brainfuck, I spent 90% of the time on transpiler useless optimization.
![](https://i.imgur.com/OezJn5W.png)

 I managed with LuaJIT to go down to 2.2s on mandelbrot (much faster than lua interpreter)

Have you tried working on a brainfuck->python transpiler instead ?

**Comment by alexprengere** [comment]
No I did not. I would not expect the performance to be different compared to the Python interpreter, since in the end the instructions executed would be similar (list manipulations). Note that I used this [BF to C transpiler](https://gist.github.com/Ricket/939687) in the benchmark, to compile the BF code to machine code.
